### ISSUE TITLE
Update docs for 11.0

### ISSUE THREAD

**Issue by susannemoog** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1082]
# Breaking

* [x] [Breaking: #23736 - Page Language detection set earlier in Frontend Request Process](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-23736-PageLanguageDetectionSetEarlierInFrontendRequestProcess.html)

* [x] [Breaking: #29342 - Improve ValidatorTask](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-29342-ImproveValidatorTask.html)

* [x] [Breaking: #89137 - Database fields t3ver_tstamp and t3ver_count dropped](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-89137-DatabaseFieldsT3verTstampAndT3verCountDropped.html)

* [x] [Breaking: #90799 - Dependency injection with non-public properties has been removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-90799-DependencyInjectionWithNonPublicPropertiesHasBeenRemoved.html)

* [ ] [Breaking: #91473 - Deprecated functionality removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-91473-DeprecatedFunctionalityRemoved.html)

* [x] [Breaking: #91562 - cObject TEMPLATE removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-91562-CObjectTEMPLATERemoved.html)

* [x] [Breaking: #91563 - PHP-based JS + CSS inclusions for Frontend removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-91563-PHP-basedJSCSSInclusionsForFrontendRemoved.html)

* [x] [Breaking: #91578 - IRRE related JavaScript has been removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-91578-IrreRelatedJavaScriptHasBeenRemoved.html)

* [x] [Breaking: #91606 - Date/time operations in FormEngine removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-91606-DatetimeOperationsInFormEngineRemoved.html)

* [x] [Breaking: #91740 - Deprecated icon identifier removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-91740-DeprecatedIconIdentifierRemoved.html)

* [x] [Breaking: #91782 - lockToDomain feature for frontend users / groups and backend users / groups removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-91782-LockToDomain.html)

* [x] [Breaking: #91906 - Store TransOrigDiffSourceField as json string](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-91906-StoreTransOrigDiffSourceFieldAsJson.html)

* [x] [Breaking: #91909 - sys_collection database tables moved into external extension](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-91909-SysCollectionDatabaseTablesMovedIntoExternalExtension.html)

* [x] [Breaking: #91974 - Configuration Option IPmaskMountGroups removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-91974-ConfigurationOptionIPmaskMountGroupsRemoved.html)

* [x] [Breaking: #92060 - Dropped class TYPO3CMSBackendViewPageTreeView](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92060-DroppedClassTYPO3CMSBackendViewPageTreeView.html)

* [x] [Breaking: #92118 - TCA ctrl thumbail setting dropped](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92118-TCACtrlThumbailSettingDropped.html)

* [x] [Breaking: #92128 - DatabaseRecordList: Drop hook to modify searchFields](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92128-DatabaseRecordListDropHookToModifySearchFields.html)

* [x] [Breaking: #92132 - Last remains of globals SOBE removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92132-LastRemainsOfGlobalsSOBERemoved.html)

* [x] [Breaking: #92206 - Remove workspace swapping of elements](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92206-RemoveWorkspaceSwappingOfElements.html)

* [x] [Breaking: #92289 - Decouple logic of ResourceFactory into StorageRepository](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92289-DecoupleLogicOfResourceFactoryIntoStorageRepository.html)

* [x] [Breaking: #92352 - New default position for redirect middleware](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92352-NewDefaultPositionForRedirectMiddleware.html)

* [x] [Breaking: #92457 - Extension Repository database table removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92457-ExtensionRepositoryDatabaseTableRemoved.html)

* [x] [Breaking: #92497 - Workspaces: Move Placeholders removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92497-WorkspacesMovePlaceholdersRemoved.html)

* [x] [Breaking: #92499 - AdminPanel does not preview hidden Frontend User Groups](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92499-AdminPanelDoesNotPreviewHiddenFrontendUserGroups.html)

* [x] [Breaking: #92502 - Make Extbase handle PSR-7 responses only](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92502-MakeExtbaseHandlePSR7ResponsesOnly.html)

* [x] [Breaking: #92513 - Method signature change of TYPO3\CMS\Extbase\Mvc\Controller\ControllerInterface::processRequest](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92513-MethodSignatureChangeOfTYPO3CMSExtbaseMvcControllerControllerInterfaceprocessRequest.html)

* [x] [Breaking: #92529 - All Fluid widget functionality removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92529-AllFluidWidgetFunctionalityRemoved.html)

* [x] [Breaking: #92532 - Support for extension-in-extension installation in Extension Manager removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92532-SupportForExtension-in-extensionInstallationInExtensionManagerRemoved.html)

* [x] [Breaking: #92558 - Database Field be_users.createdByAction removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92558-DatabaseFieldBe_userscreatedByActionRemoved.html)

* [x] [Breaking: #92559 - Removed per-user IP locking for backend users](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92559-RemovedPer-userIPLockingForBackendUsers.html)

* [x] [Breaking: #92560 - Backend editors can always delete pages recursive](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92560-BackendEditorsCanAlwaysDeletePagesRecursive.html)

* [x] [Breaking: #92582 - Resizable text area user setting dropped](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92582-ResizableTextAreaUserSettingDropped.html)

* [x] [Breaking: #92590 - Removed support for extension upload of t3x files](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92590-RemovedSupportForExtensionUploadOfT3xFiles.html)

* [x] [Breaking: #92598 - Workspace-overlays auto-fix the PID value for moved records](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92598-Workspace-overlaysAuto-fixThePIDValueForMovedRecords.html)

* [x] [Breaking: #92609 - Use controller classes when registering plugins/modules](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92609-UseControllerClassesWhenRegisteringPluginsmodules.html)

* [x] [Breaking: #45512 - No type attributes for style and link tags](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-45512-NoTypeAttributesForStyleAndLinkTags.html)

* [x] [Breaking: #92791 - “New Placeholder” records removed in Workspaces](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92791-NewPlaceholderRecordsRemovedInWorkspaces.html)

* [x] [Breaking: #92801 - Removed “Failed Login” functionality from User Authentication object](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92801-RemovedFailedLoginFunctionalityFromUserAuthenticationObject.html)

* [x] [Breaking: #92802 - User-database-based authentication timeout field removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92802-DatabaseBasedAuthenticationTimeoutFieldRemoved.html)

* [x] [Breaking: #92807 - Removed feature for keeping session data on frontend user logout](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92807-RemovedFeatureForKeepingSessionDataOnFrontendUserLogout.html)

* [x] [Breaking: #92837 - Removed setting mod.web_layout.disableAdvanced](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92837-RemoveSettingModweb_layoutdisableAdvanced.html)

* [x] [Breaking: #92838 - Additional workspace services dropped](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92838-AdditionalWorkspaceServicesDropped.html)

* [x] [Breaking: #92678 - CSS class checkbox-invert removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92678-CssClassCheckboxInvertRemoved.html)

* [x] [Breaking: #92693 - Remove LinkHandler Linktype in Linkvalidator](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92693-RemoveLinkHandlerLinktypeInLinkvalidator.html)

* [x] [Breaking: #92853 - Method canProcessRequest has been removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92853-MethodCanProcessRequestHasBeenRemoved.html)

* [x] [Breaking: #92940 - Global option “lockBeUserToDBmounts” removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92940-GlobalOptionLockBeUserToDBmountsRemoved.html)

* [x] [Breaking: #92941 - “lockToIP” UserTsConfig option removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92941-LockToIPUserTsConfigOptionRemoved.html)

* [x] [Breaking: #92989 - AbstractUserAuthentication->loginFailure removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92989-AbstractUserAuthentication-loginFailureRemoved.html)

* [x] [Breaking: #92990 - AbstractUserAuthentication->svConfig removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92990-AbstractUserAuthentication-svConfigRemoved.html)

* [x] [Breaking: #92993 - Generic search statistics from indexed search removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92993-GenericSearchStatisticsFromIndexedSearchRemoved.html)

* [x] [Breaking: #92997 - Authentication-related HTTP cache headers are emitted only by PSR-15 middlewares](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92997-Authentication-relatedHTTPCacheHeadersAreEmittedOnlyByPSR-15Middlewares.html)

* [x] [Breaking: #93002 - Support for session transfer via FE_SESSION_KEY removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-93002-SupportForSessionTransferViaFE_SESSION_KEYRemoved.html)

* [x] [Breaking: #93003 - Limitation of PageRenderer to only render full page](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-93003-LimitationOfPageRendererToOnlyRenderFullPage.html)

* [x] [Breaking: #93029 - Dropped deleted field from sys_refindex](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-93029-DroppedDeletedFieldFromSys_refindex.html)

* [x] [Breaking: #93023 - Reworked session handling](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-93023-ReworkedSessionHandling.html)

* [x] [Breaking: #93041 - Remove TypoScript option addQueryString.method](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-93041-RemoveTypoScriptOptionAddQueryStringmethod.html)

* [x] [Breaking: #93047 - Removed property sendNoCacheHeaders in AbstractUserAuthentication](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-93047-RemovedPropertySendNoCacheHeadersInAbstractUserAuthentication.html)

* [x] [Breaking: #79565 - Removed “usergroup_cached_list” database field](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-79565-RemovedUsergroup_cached_listDatabaseField.html)

* [x] [Breaking: #93048 - Backend URL rewrites](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-93048-BackendURLRewrites.html)

* [x] [Breaking: #93056 - Removed hooks when retrieving Backend user groups](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-93056-RemovedHooksWhenRetrievingBackendUserGroups.html)

* [x] [Breaking: #93062 - Various group-related public properties in BE_USER removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-93062-VariousGroup-relatedPublicPropertiesInBE_USERRemoved.html)

* [x] [Breaking: #93073 - AbstractUserAuthentication->forceSetCookie removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-93073-AbstractUserAuthentication-forceSetCookieRemoved.html)

* [x] [Breaking: #93077 - Removed unneeded configurations in PageLayoutView](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-93077-RemovedUnneededConfigurationsInPageLayoutView.html)

* [x] [Breaking: #93080 - RelationHandler internals protected](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-93080-RelationHandlerInternalsProtected.html)

* [x] [Breaking: #93081 - Removed fetching translation file mirror from typo3.org](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-93081-RemovedFetchingTranslationFileMirrorFromTypo3org.html)

* [x] [Breaking: #93083 - class.ext_update.php handling removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-93083-Classext_updatephpHandlingRemoved.html)

* [ ] [Breaking: #93093 - Rework Shortcut PHP API](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-93093-ReworkShortcutPHPAPI.html)

* [x] [Breaking: #93108 - Reworked internal user group fetching for frontend users](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-93108-ReworkedInternalUserGroupFetchingForFrontendUsers.html)

* [x] [Breaking: #93110 - Indexed search does not provide hook for EXT:crawler anymore](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-93110-IndexedSearchDoesNotProvideHookForEXTcrawlerAnymore.html)

* [x] [Breaking: #29342 - Fluid Email Template for ValidatorTask](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.0/Breaking-29342-ImproveValidatorTask.html)

* [x] [Breaking: #89137 - Database fields t3ver_tstamp and t3ver_count removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.0/Breaking-89137-DatabaseFieldsT3verTstampAndT3verCountDropped.html)

* [x] [Breaking: #92513 - Method signature change of TYPO3CMSExtbaseMvcControllerControllerInterface::processRequest](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.0/Breaking-92513-MethodSignatureChangeOfTYPO3CMSExtbaseMvcControllerControllerInterfaceprocessRequest.html)

* [x] [Breaking: #93003 - PageRenderer renders only full page](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.0/Breaking-93003-LimitationOfPageRendererToOnlyRenderFullPage.html)

# Features

* [x] [Feature: #29342 - Improve ValidatorTask](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-29342-ImproveValidatorTask.html)

* [x] [Feature: #87301 - Secure cookies enabled by default](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-87301-SecureCookiesEnabledByDefault.html)

* [x] [Feature: #88276 - TypoScript Condition for page layout](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-88276-TypoScriptConditionForPageLayout.html)

* [x] [Feature: #91712 - Redirect Module: cleanup scheduler task and CLI command](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-91712-RedirectModuleCleanupSchedulerTask.html)

* [ ] [Feature: #91719 - Custom error messages in RegularExpressionValidator](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-91719-CustomErrorMessagesInRegularExpressionValidator.html)

* [x] [Feature: #91738 - Introduce wrapper for sessionStorage](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-91738-IntroduceWrapperForSessionStorage.html)

* [x] [Feature: #91890 - Allow ordering of displayed columns in redirects overview](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-91890-ColumnOrderingInRedirectsOverview.html)

* [x] [Feature: #92022 - Show week numbers in DateTimePicker for editors](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-92022-ShowWeekNumbersInDateTimePickerForEditors.html)

* [x] [Feature: #92334 - X-Redirect-By Header for pages with redirect types](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-92334-X-Redirect-ByHeaderForPagesWithRedirectTypes.html)

* [x] [Feature: #92337 - Allow translatable labels for bookmark groups](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-92337-AllowTranslatableLabelsForBookmarkGroups.html)

* [x] [Feature: #92366 - Show fragments in preview of InputLinkElement](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-92366-ShowFragmentsInPreviewOfInputLinkElement.html)

* [x] [Feature: #92423 - Enable placeholder config for ckeditor](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-92423-EnablePlaceholderConfigForCkeditor.html)

* [x] [Feature: #92457 - Improved Extension Repository API](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-92457-ImprovedExtensionRepositoryAPI.html)

* [x] [Feature: #92462 - Add optional “defaultValues” argument to newRecord ViewHelpers](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-92462-AddOptionalDefaultValuesArgumentToNewRecordViewHelpers.html)

* [x] [Feature: #92486 - Add field control to file_collections of tt_content](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-92486-AddFieldControlToFile_collectionsOfTt_content.html)

* [x] [Feature: #92522 - Show table and field names in ext:lowlevel](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-92522-ShowTableAndFieldNamesInExtlowlevel.html)

* [x] [Feature: #92531 - Improved Email Validation](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-92531-ImprovedEmailValidation.html)

* [x] [Feature: #92538 - Show extension constraints in extension manager](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-92538-ShowExtensionConstraintsInExtensionManager.html)

* [x] [Feature: #92562 - Frontend groups resolved directly after the Frontend User itself](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-92562-FrontendGroupsResolvedDirectlyAfterTheFrontendUserItself.html)

* [x] [Feature #91859: Allow SelectCheckBox groups to be initally expanded](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-91859-AllowSelectCheckBoxGroupsToBeInitiallyExpanded.html)

* [x] [Feature: #92884 - Applications implement PSR-15 RequestHandlerInterface](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-92884-ApplicationsImplementPSR-15RequestHandlerInterface.html)

* [x] [Feature: #83814 - Add system notes creation button to modules button bar](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-83814-AddSystemNotesCreationButtonToModulesButtonBar.html)

* [x] [Feature: #89496: Make context menu usable via keyboard](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-89496-MakeContextMenuUsableViaKeyboard.html)

* [x] [Feature: #92815 - Introduce ForwardResponse for extbase](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-92815-IntroduceForwardResponseForExtbase.html)

* [x] [Feature: #92929 - Extendable configuration module](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-92929-ExtendableConfigurationModule.html)

* [x] [Feature: #92984 - PSR-7 Request available in Frontend ContentObjects](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-92984-PSR-7RequestAvailableInFrontendContentObjects.html)

* [x] [Feature: #93011 - Authentication-related cookies are attached to PSR-7 Responses](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-93011-Authentication-relatedCookiesAreAttachedToPSR-7Responses.html)

* [x] [Feature: #91810 - Introduce client-side templating engine](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-91810-IntroduceClient-sideTemplatingEngine.html)

* [x] [Feature: #93023 - Introduce UserSession and UserSessionManager](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-93023-IntroduceUserSessionAndUserSessionManager.html)
* [x] [Feature: #91810 - Introduce lit-html and lit-element as client-side templating engine](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-91810-IntroduceLit-htmlAndLit-elementAsClient-sideTemplatingEngine.html)

* [x] [Feature: #92616 - Bootstrap v5](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-92616-BootstrapV5.html)

* [x] [Feature: #93048 - Introduce Backend URL rewrites](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-93048-IntroduceBackendURLRewrites.html)

* [x] [Feature: #91712 - Cleanup scheduler task and CLI command for redirects](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.0/Feature-91712-RedirectModuleCleanupSchedulerTask.html)

* [x] [Feature #91859: Allow SelectCheckBox groups to be initially expanded](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.0/Feature-91859-AllowSelectCheckBoxGroupsToBeInitiallyExpanded.html)

* [x] [Feature: #93056 - New Event after retrieving user groups recursively](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.0/Feature-93056-NewEventAfterRetrievingUserGroupsRecursively.html)

* [x] [Feature: #93063 - FlashMessages are stored in session as JsonSerializable](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.0/Feature-93063-FlashMessagesAreStoredInSessionAsJsonSerializable.html)

# Deprecation

* [x] [Deprecation: #91606 - Global Datetime Picker initialization](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-91606-GlobalDatetimePickerInitialization.html)

* [x] [Deprecation: #91911 - optionEl of type jQuery in FormEngine.setSelectOptionFromExternalSource](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-91911-OptionElOfTypeJQueryInFormEnginesetSelectOptionFromExternalSource.html)

* [x] [Deprecation: #92062 - Migrate RecordListController hooks to an PSR-14 event](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-92062-MigrateRecordListControllerHooksToAnPSR-14Event.html)

* [x] [Deprecation: #92080 - Deprecated QueryGenerator and QueryView](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-92080-DeprecatedQueryGeneratorAndQueryView.html)

* [x] [Deprecation: #92132 - Deprecated shortcut PHP API](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-92132-DeprecatedShortcutPHPAPI.html)

* [x] [Deprecation: #92132 - Deprecated ViewHelper f:be.buttons.shortcut](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-92132-DeprecatedViewHelperFbebuttonsshortcut.html)

* [x] [Deprecation: #92435 - Deprecated StandaloneView for EmailFinisher](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-92435-DeprecatedStandaloneViewForEmailFinisher.html)

* [x] [Deprecation: #92551 - GeneralUtility methods related to pages.l18n_cfg behavior](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-92551-GeneralUtilityMethodsRelatedToPagesl18n_cfgBehavior.html)

* [x] [Deprecation: #92583 - Deprecate last arguments of wrapClickMenuOnIcon()](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-92583-DeprecateLastArgumentsOfWrapClickMenuOnIcon.html)

* [x] [Deprecation: #92598 - Workspace-related methods “fixVersioningPid”](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-92598-Workspace-relatedMethodsFixVersioningPid.html)

* [x] [Deprecation: #92607 - Deprecated GeneralUtility::uniqueList](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-92607-DeprecatedGeneralUtilityuniqueList.html)

* [x] [Deprecation: #92784 - Extbase controller actions must return ResponseInterface](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-92784-ExtbaseControllerActionsMustReturnResponseInterface.html)

* [x] [Deprecation: #92815 - ActionController::forward() is deprecated](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-92815-ActionControllerforwardIsDeprecated.html)

* [x] [Deprecation: #92922 - Use of record uid in AbstractTreeView::getIcon()](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-92922-UseOfRecordUidInAbstractTreeViewgetIcon.html)

* [x] [Deprecation: #92947 - Deprecate TYPO3_MODE and TYPO3_REQUESTTYPE constants](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-92947-DeprecateTYPO3_MODEAndTYPO3_REQUESTTYPEConstants.html)

* [x] [Deprecation: #93038 - ReferenceIndex runtime cache](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-93038-ReferenceIndexRuntimeCache.html)

* [x] [Deprecation: #93023 - Reworked session handling](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-93023-ReworkedSessionHandling.html)

* [x] [Deprecation: #89938 - Language mode in Typo3QuerySettings](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.0/Deprecation-89938-DeprecatedLanguageModeInTypo3QuerySettings.html)

* [x] [Deprecation: #92062 - Migrate RecordListController hooks to PSR-14 event](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.0/Deprecation-92062-MigrateRecordListControllerHooksToAnPSR-14Event.html)

* [x] [Deprecation: #92080 - QueryGenerator and QueryView](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.0/Deprecation-92080-DeprecatedQueryGeneratorAndQueryView.html)

* [x] [Deprecation: #92132 - Shortcut PHP API](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.0/Deprecation-92132-DeprecatedShortcutPHPAPI.html)

* [x] [Deprecation: #92132 - ViewHelper f:be.buttons.shortcut](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.0/Deprecation-92132-DeprecatedViewHelperFbebuttonsshortcut.html)

* [x] [Deprecation: #92386 - Extbase property injection](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.0/Deprecation-92386-DeprecatedExtbasePropertyInjection.html)

* [x] [Deprecation: #92435 - StandaloneView for EmailFinisher](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.0/Deprecation-92435-DeprecatedStandaloneViewForEmailFinisher.html)

* [x] [Deprecation: #92583 - 3 last arguments of wrapClickMenuOnIcon()](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.0/Deprecation-92583-DeprecateLastArgumentsOfWrapClickMenuOnIcon.html)

* [x] [Deprecation: #92607 - GeneralUtility::uniqueList](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.0/Deprecation-92607-DeprecatedGeneralUtilityuniqueList.html)

* [x] [Deprecation: #92815 - ActionController::forward()](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.0/Deprecation-92815-ActionControllerForward.html)

* [x] [Deprecation: #92947 - TYPO3_MODE and TYPO3_REQUESTTYPE constants](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.0/Deprecation-92947-DeprecateTYPO3_MODEAndTYPO3_REQUESTTYPEConstants.html)

* [x] [Deprecation: #93060 - Shortcut title must be set by controllers](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.0/Deprecation-93060-ShortcutTitleMustBeSetByControllers.html)

* [x] [Deprecation: #93093 - MethodName in Shortcut PHP API](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.0/Deprecation-93093-DeprecateMethodNameInShortcutPHPAPI.html)

# Important

* [x] [Important: #91888 - System extension “about” merged into “backend” system extension](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Important-91888-SystemExtensionAboutMergedIntoBackendSystemExtension.html)

* [x] [Important: #91953 - jQuery updated to 3.5.x](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Important-91953-JQueryUpdatedTo35x.html)
* [x] [Important: #92736 - Return timestamp as integer in DateTimeAspect](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Important-92736-ReturnTimestampAsIntegerInDateTimeAspect.html)

* [x] [Important: #92870 - Always use Fluid based page module](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Important-92870-AlwaysUseFluidBasedPageModule.html)

* [x] [Important: #92996 - Properties and methods in ActionController marked internal](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Important-92996-PropertiesAndMethodsInActionControllerMarkedInternal.html)

* [x] [Important: #89938 - Removed dead code from Extbase persistence](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.0/Important-89938-RemovedDeadCodeFromExtbasePersistence.html)

* [x] [Important: #93121 - Workspace records are discarded](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.0/Important-93121-WorkspaceRecordsAreDiscarded.html)

**Comment by linawolf** [comment]
All messages have been merged in, closing
