### ISSUE TITLE
Update docs for 11.1

### ISSUE THREAD

**Issue by susannemoog** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1303]
# Breaking

# Features

* [x] [Feature: #78036 - Synchronize folder relations after rename](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-78036-SynchronizeFolderRelationsAfterRename.html)

* [x] [Feature: #78760 - Resizable Navigation Component](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-78760-ResizableNavigationComponent.html) (not documented)

* [x] [Feature: #89509 - Data Processor to resolve FlexForm data](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-89509-DataProcessorToResolveFlexFormData.html)

* [x] [Feature: #92338 - Allow link text wrapping in TypolinkViewhelper](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-92338-AllowLinkTextWrappingInTypolinkViewhelper.html) (see viewhelper inline docs)

* [x] [Feature: #92628 - Add Alt-Text To Login Logo](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-92628-AddAltTextToLoginLogo.html) (not documented)

* [x] [Feature: #92704 - Improve keyboard navigation for module menus](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-92704-ImproveKeyboardNavigationForModuleMenus.html) (not documented)

* [x] [Feature: #92942 - Allow icon overlay for newContentElementWizard elements](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-92942-AllowIconOverlayForNewContentElementWizardElements.html)

* [x] [Feature: #93117 - Add reset button to Backend User module filter](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-93117-AddResetButtonToBackendUserModuleFilter.html)

* [x] [Feature: #93174 - Lazy console command list](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-93174-LazyConsoleCommandList.html)

* [x] [Feature: #93426 - SVG-based Tree for Folder Navigation with Filter](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-93426-SVG-basedTreeForFolderNavigationWithFilter.html)

* [x] [Feature: #93455 - Backend Routes restricted to specified HTTP methods](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-93455-BackendRoutesRestrictedToSpecifiedHTTPMethods.html) (backend routing as a whole will be documented for v11 LTS instead of step-by-step during the cycle)

* [x] [Feature: #93526 - Multi-Factor Authentication](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-93526-MultiFactorAuthentication.html)

# Deprecation

* [x] [Deprecation: #92628 - Login Logo without Alt-Text](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-92628-LoginLogoWithoutAltText.html)

* [x] [Deprecation: #93149 - T3Editor JavaScript module replaced by CodeMirrorElement](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-93149-T3EditorModuleReplacedByReplacedByCodeMirrorElement.html) (not documented, however, CodeMirrorElement should probably be documented at a later point)

* [x] [Deprecation: #93454 - Rename Sortable to sortablejs](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-93454-RenameSortableToSortablejs.html)

* [x] [Deprecation: #93506 - jQuery in tooltips](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-93506-JQueryInTooltips.html)

# Important

**Comment by linawolf** [comment]
Everything is checked and merged so this is done
