### ISSUE TITLE
Update docs for 11.2 (ongoing master issue)

### ISSUE THREAD

**Issue by susannemoog** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1353]
# Breaking

# Features

* [x] [Feature: #57082 - New TCA type “language”](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-57082-NewTCATypeLanguage.html)

* [x] [Feature: #93188 - Possibility to disable hreflang per page](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-93188-PossibilityToDisableHreflangPerPage.html)

* [x] [Feature: #93591 - Allow group id lookup in conditions with array operator](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-93591-AllowGroupIdLookupInConditionsWithArrayOperator.html)

* [x] [Feature: #93663 - Backend Users preferred UI language stored as DB field](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-93663-BackendUsersPreferredUILanguageStoredAsDBField.html)

* [x] [Feature: #93606 - Possibility to disable canonical per page](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-93606-PossibilityToDisableCanonicalPerPage.html)

* [x] [Feature: #93794 - Override TCA description with TSconfig](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-93794-OverrideTCADescriptionWithTSconfig.html)

* [x] [Feature: #93651 - Provide list of available system locales](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-93651-ProvideListOfAvailableSystemLocales.html)

* [x] [Feature: #93857 - Resizable navigation component for all element / record selectors](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-93857-ResizableNavigationComponentForAllElementRecordSelectors.html)

* [x] [Feature: #73176 - Filterable Trees in Record Selectors and Link Pickers](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-73176-FilterableTreesInRecordSelectorsAndLinkPickers.html)

* [x] [Feature: #89762 - Add pagination for FormManagement](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-89762-AddPaginationForFormManagement.html)

* [x] [Feature: #93209 - FAL: Add getFile() to TYPO3CMSCoreResourceFolder](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-93209-FALAddGetFileToTYPO3CMSCoreResourceFolder.html)

* [x] [Feature: #93988 - Backend module URLs reflect into browser adressbar](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-93988-BackendModuleURLsReflectIntoBrowserAdressbar.html)

* [x] [Feature: #93908 - Add decoding attribute to images](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-93908-Image-decoding-attribute.html)

# Deprecation

* [x] [Deprecation: #93726 - Deprecated TypoScriptParser related properties](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-93726-DeprecatedTypoScriptParserRelatedProperties.html)

* [x] [Deprecation: #93837 - Deprecated special property of TCA type select](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-93837-DeprecatedSpecialPropertyOfTCATypeSelect.html)

* [x] [Deprecation: #93899 - FormEngine’s requestConfirmationOnFieldChange deprecated](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-93899-FormEnginesRequestConfirmationOnFieldChangeDeprecated.html)

* [x] [Deprecation: #92992 - Hook t3lib_parsehtml_proc.php:transformation](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-92992-HookT3libclasst3lib_parsehtml_procphptransformation.html)

* [x] [Deprecation: #93944 - File Tree as iframe migrated to SVG-based tree](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-93944-FileTreeAsIframeMigratedToSVG-basedTree.html)

* [x] [Deprecation: #93975 - Deprecated TBE_EDITOR.fieldChanged()](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-93975-DeprecatedTBE_EDITORfieldChanged.html)

* [x] [Deprecation: #92494 - Extbase EnvironmentService](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-92494-ExtbaseEnvironmentService.html)

# Important

* [x] [Important: #88824 - Add cache for error page handling](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Important-88824-AddCacheForErrorPageHandling.html)

* [x] [Important: #93398 - Possibility to ignore submitted values in HiddenViewHelper](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Important-93398-PossibilityToIgnoreSubmittedValuesInHiddenViewHelper.html)

**Comment by linawolf** [comment]
**Deprecation: #93726 - Deprecated TypoScriptParser related properties**

These properties didn't get mentioned in the TYPO3 Core Api and seem to not have been used, really

**Comment by linawolf** [comment]
Feature: #93651 - Provide list of available system locales 
no need to document, there are no real changes for users or developers.
Feature: #93857 - Resizable navigation component for all element / record selectors
No need to dokument this

**Comment by linawolf** [comment]
Deprecation: #93899 - FormEngine’s requestConfirmationOnFieldChange deprecated
Has not been mentioned in the docs as far as I can see

**Comment by linawolf** [comment]
Feature: #89762 - Add pagination for FormManagement doesn't need to be documented

**Comment by linawolf** [comment]
Feature: #93988 - Backend module URLs reflect into browser adressbar needs not be documented

**Comment by linawolf** [comment]
Deprecation: #92992 - Hook t3lib_parsehtml_proc.php:transformation the according page has already been removed from master as this did not work anymore, anyway

**Comment by linawolf** [comment]
Deprecation: #93944 - File Tree as iframe migrated to SVG-based tree we don't have this documented and I think its not needed

**Comment by linawolf** [comment]
Deprecation: #93975 - Deprecated TBE_EDITOR.fieldChanged() this doesn't seem to be mentioned anywhere

**Comment by linawolf** [comment]
Important: #93398 - Possibility to ignore submitted values in HiddenViewHelper is automatically integrated here: https://docs.typo3.org/other/typo3/view-helper-reference/master/en-us/typo3/fluid/latest/Form/Hidden.html#respectsubmitteddatavalue

**Comment by linawolf** [comment]
Deprecation: #92494 - Extbase EnvironmentService doesnt need to be documented the class was @internal and not documented anyway

**Comment by linawolf** [comment]
Feature: #93908 - Add decoding attribute to images is automatically documented in the viewhelper
