### ISSUE TITLE
Update docs for 11.3

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1395]
# Features

* [x] [Feature: #92358 - Add getModuleTemplate() to PageLayoutController](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Feature-92358-AddGetModuleTemplateToPageLayoutController.html)

* [x] [Feature: #92518 - Download and filename options added to FileDumpController](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Feature-92518-DownloadAndFilenameOptionsAddedToFileDumpController.html)

* [x] [Feature: #92518 - Introduce FileViewHelper](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Feature-92518-IntroduceFileViewHelper.html)

* [x] [Feature: #93114 - Native Support for Language Shona (Bantu) added](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Feature-93114-NativeSupportForLanguageShonaBantuAdded.html)

* [x] [Feature: #93210 - Possibility to refresh dashboard widgets](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Feature-93210-PossibilityToRefreshDashboardWidgets.html)

* [x] [Feature: #93668 - Possibility to configure Symfony mailer](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Feature-93668-PossibilityToConfigureSymfonyMailer.html)

* [x] [Feature: #93835 - AddErrorForProperty function for AbstractValidator](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Feature-93835-AddErrorForPropertyFunctionForAbstractValidator.html)

* [x] [Feature: #93921 - Sharing backend links](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Feature-93921-SharingBackendLinks.html)

* [x] [Feature: #94081 - TCA readOnly for t3editor](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Feature-94081-TCAReadOnlyForT3editor.html)

* [x] [Feature: #94143 - Display creation date of redirects](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Feature-94143-DisplayCreationDateOfRedirects.html)

* [x] [Feature: #94206 - Add excludePagesRecursive option to XML sitemap generation](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Feature-94206-AddExcludePagesRecursiveOptionToSitemapGeneration.html)

* [x] [Feature: #94210 - Information about inherited backend layout](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Feature-94210-InformationAboutInheritedBackendLayout.html)

* [x] [Feature: #94218 - Selectable columns per table in record list](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Feature-94218-SelectableColumnsPerTableInRecordList.html)

* [x] [Feature: #89700 - Show Layouts in the Web Info Module](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Feature-89700-ShowLayoutsInTheWebInfoModule.html)

* [x] [Feature: #93631 - Support for PHP 8.0](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Feature-93631-SupportForPHP80.html)

* [x] [Feature: #94345 - Auto-detect event types](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Feature-94345-AutoDetectEventTypes.html)

* [x] [Feature: #94374 - Create new filemount via folders’ context menu](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Feature-94374-CreateNewFilemountViaFoldersContextMenu.html)

* [x] [Feature: #94390 - Dropdown for record list and file list in favor of Extended View](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Feature-94390-DropdownForRecordListAndFileListInFavorOfExtendedView.html)
 

* [x] [Feature: #89507 - Add description for TCA palettes](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Feature-89507-AddDescriptionForTCAPalettes.html)

* [x] [Feature: #94411 - Recordlist export settings](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Feature-94411-RecordlistExportSettings.html)

* [x] [Feature: #94428 - Extbase Request implements ServerRequestInterface](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Feature-94428-ExtbaseRequestImplementsServerRequestInterface.html)

* [x] [Feature: #94447 - Native Support for Language Welsh added](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Feature-94447-NativeSupportForLanguageWelshAdded.html)

* [x] [Feature: #94452 - Improved Multi-Selection in File Selection](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Feature-94452-ImprovedMulti-SelectionInFileSelection.html)

* [x] [Feature: #94474 - Improved show columns selection in record list](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Feature-94474-ImprovedShowColumnsSelectionInRecordList.html)

* [x] [Feature: #89700 - Show layouts in the Web Info module](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Feature-89700-ShowLayoutsInTheWebInfoModule.html)

* [x] [Feature: #93825 - Rate limiting for failed logins](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Feature-93825-RateLimitingForFailedLogins.html)

* [x] [Feature: #94411 - Record list download settings](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Feature-94411-RecordlistDownloadSettings.html)

* [x] [Feature: #94524 - Edit metadata for a file via the context menu](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Feature-94524-EditMetadataForAFileViaTheContextMenu.html)

# Deprecation

* [x] [Deprecation: #91806 - BackendUtility viewOnClick](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Deprecation-91806-BackendUtilityViewOnClick.html)

* [x] [Deprecation: #94058 - JavaScript goToModule()](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Deprecation-94058-JavaScriptGoToModule.html)

* [x] [Deprecation: #94137 - Switch behavior of ArrayUtility::arrayDiffAssocRecursive()](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Deprecation-94137-SwitchBehaviorOfArrayUtilityarrayDiffAssocRecursive.html)

* [x] [Deprecation: #94165 - sys_language table](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Deprecation-94165-SysLanguageDatabaseTable.html)

* [x] [Deprecation: #94193 - Public url with relative paths in FAL API](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Deprecation-94193-PublicUrlWithRelativePathsInFALAPI.html)

* [x] [Deprecation: #94209 - Backend ModuleLayout ViewHelpers](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Deprecation-94209-BackendModuleLayoutViewHelpers.html)

* [x] [Deprecation: #94223 - Extbase Request->getBaseUri()](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Deprecation-94223-ExtbaseRequest-getBaseUri.html)

* [x] [Deprecation: #94225 - f:be.container ViewHelper](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Deprecation-94225-FbecontainerViewHelper.html)

* [x] [Deprecation: #94227 - f:base ViewHelper](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Deprecation-94227-FbaseViewHelper.html)

* [x] [Deprecation: #94228 - Deprecate extbase request getRequestUri()](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Deprecation-94228-DeprecateExtbaseRequestGetRequestUri.html)

* [x] [Deprecation: #94231 - Deprecate extbase InvalidRequestMethodException](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Deprecation-94231-DeprecateExtbaseInvalidRequestMethodException.html)

* [x] [Deprecation: #94252 - Deprecated GeneralUtility::compileSelectedGetVarsFromArray](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Deprecation-94252-DeprecatedGeneralUtilitycompileSelectedGetVarsFromArray.html)

* [x] [Deprecation: #94272 - Deprecated Application->run callback](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Deprecation-94272-DeprecatedApplication-runCallback.html)

* [x] [Deprecation: #94309 - Deprecated GeneralUtility::stdAuthCode](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Deprecation-94309-DeprecatedGeneralUtilitystdAuthCode.html)

* [x] [Deprecation: #94311 - Deprecated GeneralUtility::rmFromList](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Deprecation-94311-DeprecatedGeneralUtilityrmFromList.html)

* [x] [Deprecation: #94313 - AbstractService class](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Deprecation-94313-ClassAbstractService.html)

* [x] [Deprecation: #94317 - ext:form Finisher implementations](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Deprecation-94317-ExtformFinisherImplementations.html)

* [x] [Deprecation: #94115 - Parameter Type Evaluation via DocBlock comments](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Deprecation-94115-ParameterTypeEvaluationViaDocBlockComments.html)

* [x] [Deprecation: #94316 - Deprecated HTTP header manipulating methods from HttpUtility](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Deprecation-94316-DeprecatedHTTPHeaderManipulatingMethodsFromHttpUtility.html)

* [x] [Deprecation: #94351 - ext:extbase StopActionException](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Deprecation-94351-ExtextbaseStopActionException.html)

* [x] [Deprecation: #94367 - extbase ReferringRequest](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Deprecation-94367-ExtbaseReferringRequest.html)

* [x] [Deprecation: #94377 - extbase ObjectManager->getEmptyObject](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Deprecation-94377-ExtbaseObjectManager-getEmptyObject.html)

* [x] [Deprecation: #94394 - Extbase Request setDispatched() and isDispatched()](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Deprecation-94394-ExtbaseRequestSetDispatchedAndIsDispatched.html)

* [x] [Deprecation: #94414 - Deprecate LanguageService Container Entry](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Deprecation-94414-DeprecateLanguageServiceContainerEntry.html)

# Important

* [x] [Important: #91496 - Changes to password reset functionality](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Important-91496-ChangesToPasswordResetFunctionality.html)

* [x] [Important: #93854 - Add disabled option for allowed aspect ratios](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Important-93854-AddDisabledOptionForAllowedAspectRatios.html)

* [x] [Important: #94312 - Removed BE/loginSecurityLevel and FE/loginSecurityLevel options](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Important-94312-RemovedBEloginSecurityLevelAndFEloginSecurityLevelOptions.html)

* [x] [Important: #94315 - Use proper PSR-3 logging messages and context](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Important-94315-UseProperPSR-3LoggingMessagesAndContext.html)

**Comment by linawolf** [comment]
Feature: #93114 - Native Support for Language Shona (Bantu) added doesn't need to be documented, just a new language

**Comment by linawolf** [comment]
Feature: #93210 - Possibility to refresh dashboard widgets -> https://review.typo3.org/c/Packages/TYPO3.CMS/+/69233

**Comment by linawolf** [comment]
https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TCA/pull/393/commits

**Comment by linawolf** [comment]
Feature: #94143 - Display creation date of redirects does not need to be documented

**Comment by linawolf** [comment]
Deprecation: #94137 - Switch behavior of ArrayUtility::arrayDiffAssocRecursive() will be documented in the automatically generated API

**Comment by linawolf** [comment]
Add getModuleTemplate() to PageLayoutController: Not documented anywhere

**Comment by linawolf** [comment]
Feature: #92518 - Download and filename options added to FileDumpController is not documented anywhere

**Comment by linawolf** [comment]
Feature: #92518 - Introduce FileViewHelper New Viewhelpers get documented automatically

**Comment by linawolf** [comment]
Feature: #93835 - AddErrorForProperty function for AbstractValidator the old way is not documented either

**Comment by linawolf** [comment]
Feature: #94206 - Add excludePagesRecursive option to XML sitemap generation Needs to be documented in the seo extension

**Comment by linawolf** [comment]
Feature: #94210 - Information about inherited backend layout

doesn't need to be documented

**Comment by linawolf** [comment]
Deprecation: #91806 - BackendUtility viewOnClick is not part of the official documentation

**Comment by linawolf** [comment]
Deprecation: #94058 - JavaScript goToModule() not part of documentation

**Comment by linawolf** [comment]
Deprecation: #94227 - f:base ViewHelper, Deprecation: #94225 - f:be.container ViewHelper
Viewhelper documentation gets rendered automatically

**Comment by linawolf** [comment]
Deprecation: #94231 - Deprecate extbase InvalidRequestMethodException not mentioned in docs

**Comment by linawolf** [comment]
Deprecation: #94252 - Deprecated GeneralUtility::compileSelectedGetVarsFromArray was never mentioned in the docs

**Comment by linawolf** [comment]
Deprecation: #94272 - Deprecated Application->run callback was never mentioned in the docs

**Comment by linawolf** [comment]
Feature: #89700 - Show Layouts in the Web Info Module Doesn't need to be documented

**Comment by linawolf** [comment]
Deprecation: #94193 - Public url with relative paths in FAL API is not documented

**Comment by linawolf** [comment]
Was not mentioned: Deprecation: #94223 - Extbase Request->getBaseUri()

**Comment by linawolf** [comment]
Was not mentioned: Deprecation: #94309 - Deprecated GeneralUtility::stdAuthCode

**Comment by linawolf** [comment]
Deprecation: #94311 - Deprecated GeneralUtility::rmFromList was not mentioned in docs

**Comment by linawolf** [comment]
Deprecation: #94317 - ext:form Finisher implementations - can be documented in the extensions documentation

**Comment by linawolf** [comment]
Has not been mentioned: Deprecation: #94367 - extbase ReferringRequest

**Comment by linawolf** [comment]
Has not been mentioned: Deprecation: #94377 - extbase ObjectManager->getEmptyObject

**Comment by linawolf** [comment]
has not been mentioned: Deprecation: #94394 - Extbase Request setDispatched() and isDispatched()

**Comment by linawolf** [comment]
doesn't need to be documented:  Feature: #93921 - Sharing backend links

**Comment by linawolf** [comment]
Deprecation: #94414 - Deprecate LanguageService Container Entry has not been mentioned

**Comment by linawolf** [comment]
Feature: #94447 - Native Support for Language Welsh added Need so documentation

**Comment by linawolf** [comment]
https://docs.typo3.org/m/typo3/reference-tca/master/en-us/Palettes/Properties/Description.html needs no documentation

**Comment by linawolf** [comment]
Feature: #94524 - Edit metadata for a file via the context menu Documentation not needed

**Comment by linawolf** [comment]
Does not need to be documented: Feature: #94428 - Extbase Request implements ServerRequestInterface

**Comment by linawolf** [comment]
We are finished here

**Comment by susannemoog** [comment]
👯‍♀️ thank you!
