### ISSUE TITLE
Update docs for 11.4 (ongoing master issue)

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1449]
New changelogs
# Breaking

* [x] [Breaking: #70528 - Deprecated form mixins removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-70528-DeprecatedFormMixinsRemoved.html)

# Features

* [x] [Feature: #94406 - Override fileFolder TCA configuration with TSconfig](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-94406-OverrideFileFolderTCAConfigurationWithTSconfig.html)

* [x] [Feature: #94489 - Filter for redirects never hit](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-94489-FilterForRedirectsNeverHit.html)

* [x] [Feature: #90336 - CKEditor Autolinking uses https by default](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-90336-CKEditorAutolinkingUsesHttpsByDefault.html)

* [x] [Feature: #71775 - HtmlParser allows srcset](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-71775-HtmlParserAllowsSrcset.html)

* [x] [Feature: #94590 - Allow icon identifiers in report module registration](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-94590-AllowIconIdentifiersInReportModuleRegistration.html)

* [x] [Feature: #94653 - Autocomplete attribute for PasswordViewHelper](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-94653-AutocompleteAttributeForPasswordViewHelper.html)

* [x] [Feature: #90347 - Enable recursive transformation of properties in JsonView](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-90347-EnableRecursiveTransformationOfPropertiesInJsonView.html)

* [x] [Feature: #92460 - Split default from all languages in page module](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-92460-SplitDefaultFromAllLanguagesInPageModule.html)

* [x] [Feature: #94622 - New TCA type “category”](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-94622-NewTCATypeCategory.html)

* [x] [Feature: #94623 - tt_content images, assets, media showPossibleLocalizationRecords](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-94623-Tt_contentImagesAssetsMediaShowPossibleLocalizationRecords.html)

* [x] [Feature: #94680 - Show columns selector filter](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-94680-ShowColumnsSelectorFilter.html)

* [x] [Feature: #94692 - Registering Icons via Service Container](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-94692-RegisteringIconsViaServiceContainer.html)

* [x] [Feature: #84115 - Doctrine DBAL - notInSet() for expressions](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-84115-DoctrineDBAL-NotInSetForExpressions.html)

* [x] [Feature: #94577 - Clear indexed_search documents when content is changed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-94577-ClearIndexed_searchDocumentsWhenContentIsChanged.html)

* [x] [Feature: #94741 - Register SoftReference parsers via DI](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-94741-RegisterSoftReferenceParsersViaDI.html)

* [x] [Feature: #94765 - Introduce showNewRecordLink option](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-94765-IntroduceShowNewRecordLinkOption.html)

* [x] [Feature: #94819 - Improved Workspaces module](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-94819-ImprovedWorkspacesModule.html)

* [x] [Feature: #84184 - Show columns selection in filelist](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-84184-ShowColumnsSelectionInFilelist.html)

* [x] [Feature: #84718 - Add CLI export command to EXT:impexp](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-84718-AddCLIExportCommandToImpExpExtension.html)

* [x] [Feature: #91021 - Filter by stage in Workspaces Module](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-91021-FilterByStageInWorkspacesModule.html)

* [x] [Feature: #94662 - Add placeholder for site configuration in foreign_table_where](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-94662-AddPlaceholderForSiteConfigurationInForeignTableWhere.html)

* [x] [Feature: #94906 - Multi record selection in filelist](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-94906-MultiRecordSelectionInFilelist.html)

* [x] [Feature: #94944 - Keyboard shortcuts for multi record selection](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-94944-KeyboardShortcutsForMultiRecordSelection.html)

* [x] [Feature: #94996 - Consider all Composer installed extensions as active](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-94996-ConsiderAllComposerInstalledExtensionsAsActive.html)

* [x] [Feature: #90197 - Introduce cache:flush console command](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-90197-IntroduceCacheFlushConsoleCommand.html)

* [x] [Feature: #90548 - Download multiple files and folders in filelist](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-90548-DownloadMultipleFilesAndFoldersInFilelist.html)

* [x] [Feature: #93197 - Resolve collection types of non-persistent objects](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-93197-ResolveCollectionTypesOfNon-persistentObjects.html)

* [x] [Feature: #93436 - Introduce cache:warmup console command](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-93436-IntroduceCacheWarmupConsoleCommand.html)

* [x] [Feature: #94402 - Generated Error pages via TYPO3-internal subrequest](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-94402-GeneratedErrorPagesViaTYPO3-internalSubrequest.html)

* [x] [Feature: #94889 - Add “result” option to typolink returnLast parameter](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-94889-AddResultOptionToTypolinkReturnLastParameter.html)

* [x] [Feature: #94966 - Show debugger in Application Information](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-94966-ShowDebuggerInApplicationInformation.html)

* [x] [Feature: #95034 - List views: Select a row by clicking on it](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-95034-SelectRowByMouseClick.html)

* [x] [Feature: #95035 - “Collapse all” for large trees](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-95035-CollapseAllForLargeTrees.html)

* [x] [Feature: #95037 - New startingPoints setting for FormEngine treeConfig](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-95037-NewStartingPointsSettingForFormEngineTreeConfig.html)

* [x] [Feature: #95044 - Support autowired LoggerInterface injection](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-95044-SupportAutowiredLoggerInterfaceInjection.html)

* [x] [Feature: #95061 - Auto creation of MM tables from TCA](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-95061-AutoCreationOfMMTablesFromTCA.html)

* [x] [Feature: #95065 - New PSR-14 BootCompletedEvent](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-95065-NewPSR-14BootCompletedEvent.html)

* [x] [Feature: #95068 - Multi record selection in recordlist](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-95068-MultiRecordSelectionInRecordlist.html)

* [x] [Feature: #95077 - New PSR-14 ProcessFileListActionsEvent](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-95077-NewPSR-14ProcessFileListActionsEvent.html)

* [x] [Feature: #95079 - Support PHP 8 style Channel attribute for logger injection](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-95079-SupportPHP8StyleChannelAttributeForLoggerInjection.html)

* [x] [Feature: #95077 - New PSR-14 ModifyFileDumpEvent](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-95080-NewPSR-14ModifyFileDumpEvent.html)

* [x] [Feature: #95083 - New PSR-14 ModifyClearCacheActionsEvent](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-95083-NewPSR-14ModifyClearCacheActionsEvent.html)

* [x] [Feature: #95089 - New PSR-14 AfterFileCommandProcessedEvent](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-95089-NewPSR-14AfterFileCommandProcessedEvent.html)

* [ ] [Feature: #95105 - New PSR-14 DatabaseRecordList events](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.4/Feature-95105-NewPSR-14DatabaseRecordListEvents.html)

# Deprecation

* [x] [Deprecation: #94619 - Extbase ObjectManager](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-94619-ExtbaseObjectManager.html)

* [x] [Deprecation: #94654 - Generic extbase domain classes](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-94654-GenericExtbaseDomainClasses.html)

* [x] [Deprecation: #94664 - Pdo cache backend](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-94664-PdoCacheBackend.html)

* [x] [Deprecation: #94665 - Wincache cache backend](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-94665-WincacheCacheBackend.html)

* [x] [Deprecation: #85613 - Category Registry](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-85613-CategoryRegistry.html)

* [x] [Deprecation: #94684 - GeneralUtility::shortMD5()](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-94684-GeneralUtilityShortMD5.html)

* [x] [Deprecation: #94687 - Deprecate SoftReferenceIndex](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-94687-SoftReferenceIndex.html)

* [x] [Deprecation: #94741 - Register SoftReference parsers via DI](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-94741-RegisterSoftReferenceParsersViaDI.html)

* [x] [Deprecation: #94762 - Deprecate JavaScript top.fsMod state](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-94762-DeprecateJavaScriptTopfsModState.html)

* [x] [Deprecation: #94902 - Deprecate lowerCamelCase options of EXT:impexp commands](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-94902-LowerCamelCaseOptionsOfExtImpExpCommands.html)

* [x] [Deprecation: #94953 - Edit panel related frontend functionality](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-94953-EditPanelRelatedFrontendFunctionality.html)

* [x] [Deprecation: #94956 - Public $cObj](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-94956-PublicCObj.html)

* [x] [Deprecation: #94957 - TypoScriptFrontendController->cObjectDepthCounter](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-94957-TypoScriptFrontendController-cObjectDepthCounter.html)

* [x] [Deprecation: #94958 - ContentObjectRenderer properties](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-94958-ContentObjectRendererProperties.html)

* [x] [Deprecation: #94959 - ContentObjectRenderer constructor in StandaloneView](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-94959-ContentObjectRendererConstructorInStandaloneView.html)

* [x] [Deprecation: #94979 - Using CacheManager or Database Connections during TYPO3 bootstrap](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-94979-UsingCacheManagerOrDatabaseConnectionsDuringTYPO3Bootstrap.html)

* [x] [Deprecation: #94991 - Extbase AbstractView](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-94991-ExtbaseAbstractView.html)

* [x] [Deprecation: #94996 - In Composer Mode, all Extensions should be installed with Composer](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-94996-InComposerModeAllExtensionsShouldBeInstalledWithComposer.html)

* [x] [Deprecation: #95003 - Extbase ViewInterface canRender()](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-95003-ExtbaseViewInterfaceCanRender.html)

* [x] [Deprecation: #95005 - Extbase EmptyView](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-95005-ExtbaseEmptyView.html)

* [x] [Deprecation: #95011 - Various global JavaScript functions and variables](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-95011-VariousGlobalJavaScriptFunctionsAndVariables.html)

* [x] [Deprecation: #95037 - rootUid related setting of trees](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-95037-RootUidRelatedSettingOfTrees.html)

* [x] [Deprecation: #95062 - $skipSorting argument of RelationHandler->writeForeignField()](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-95062-SkipSortingArgumentOfRelationHandler-writeForeignField.html)

* [x] [Deprecation: #95065 - Hook extTablesInclusion-PostProcessing](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-95065-HookExtTablesInclusion-PostProcessing.html)

* [x] [Deprecation: #95077 - Filelist editIconsHook](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-95077-FilelistEditIconsHook.html)

* [x] [Deprecation: #95077 - FileDump CheckFileAccess hook](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-95080-FileDumpCheckFileAccessHook.html)

* [x] [Deprecation: #95083 - Backend toolbar CacheActions hook](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-95083-BackendToolbarCacheActionsHook.html)

* [x] [Deprecation: #95089 - ExtendedFileUtility ProcessData hook](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-95089-ExtendedFileUtilityProcessDataHook.html)

* [x] [Deprecation: #95009 - Passing TypoScript configuration as constructor argument to Exception handler](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.4/Deprecation-95009-PassingTypoScriptConfigurationAsConstructorArgumentToExceptionHandler.html)

* [x] [Deprecation: #95105 - DatabaseRecordList hooks](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.4/Deprecation-95105-DatabaseRecordListHooks.html)

# Important

* [x] [Important: #94615 - Fluid view helpers f:link.external and f:uri.external use https by default](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Important-94615-FluidViewHelpersFlinkexternalAndFuriexternalUseHttpsByDefault.html)

* [x] [Important: #92202 - Remove exclude from important fields](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Important-92202-RemoveExcludeFromImportantFields.html)

* [x] [Important: #90264 - Initialize datepicker JS in external file](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Important-90264-InitializeDatepickerJSInExternalFile.html)

* [x] [Important: #94697 - Quote database identifiers when used instead of globally upfront](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Important-94697-QuoteDatabaseIdentifiersWhenUsedInsteadOfGloballyUpfront.html)

* [x] [Important: #94830 - Update egulias/email-validator](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Important-94830-UpdateEguliasemail-validator.html)

* [x] [Important: #94280 - Move contents of ext_*.php into global namespace](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Important-94280-MoveContentsOfExtPhpIntoLocalScopes.html)

* [x] [Important: #94876 - Remove “Non-XML text” validator from form editor](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Important-94876-RemoveNon-XMLTextValidatorFromFormEditor.html)

* [x] [Important: #94889 - AbstractTypoLinkBuilder::build now returns array|LinkResultInterface](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Important-94889-LinkBuilderbuildNowReturnsArrayLinkResultInterface.html)

* [ ] [Important: #95647 - Composer installations and extension usage](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.4/Important-95647-ComposerInstallationsAndExtensionUsage.html)

**Comment by linawolf** [comment]
Feature: #94489 - Filter for redirects never hit doesnt need to be documented

**Comment by linawolf** [comment]
Not documented: Feature: #71775 - HtmlParser allows srcset

**Comment by linawolf** [comment]
Needs no documentation

**Comment by linawolf** [comment]
not documented: Feature: #94590 - Allow icon identifiers in report module registration

**Comment by linawolf** [comment]
Willl be automatically documented in the ViewHelper Reference: Feature: #94653 - Autocomplete attribute for PasswordViewHelper

**Comment by linawolf** [comment]
Will be documented in the View Helper Reference: Important: #94615 - Fluid view helpers f:link.external and f:uri.external use https by default

**Comment by linawolf** [comment]
Important: #92202 - Remove exclude from important fields doesnt need to be documented

**Comment by linawolf** [comment]
I dont think we need to document this: Important: #94697 - Quote database identifiers when used instead of globally upfront

**Comment by linawolf** [comment]
Important: #94830 - Update egulias/email-validator doesn't need to be documented

**Comment by linawolf** [comment]
Important: #90264 - Initialize datepicker JS in external file can be documented in the form Documentation

**Comment by linawolf** [comment]
Important: #94876 - Remove “Non-XML text” validator from form editor -> Manual of extension forms

**Comment by linawolf** [comment]
Important: #94889 - AbstractTypoLinkBuilder::build now returns array|LinkResultInterface -> is not found in the manuals

**Comment by linawolf** [comment]
Deprecation: #94654 - Generic extbase domain classes arent mentioned

**Comment by linawolf** [comment]
Deprecation: #94664 - Pdo cache backend not mentioned in the docs

**Comment by linawolf** [comment]
Deprecation: #94684 - GeneralUtility::shortMD5() wasn't mentioned

**Comment by linawolf** [comment]
Deprecation: #94687 - Deprecate SoftReferenceIndex was already documented in https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/1487

**Comment by linawolf** [comment]
Deprecation: #94762 - Deprecate JavaScript top.fsMod state was not mentioned

**Comment by linawolf** [comment]
Deprecation: #94956 - Public $cObj wasn't mentioned

**Comment by linawolf** [comment]
Deprecation: #94957 - TypoScriptFrontendController->cObjectDepthCounter wasn't mentioned

**Comment by linawolf** [comment]
Deprecation: #94958 - ContentObjectRenderer properties have never been mentioned

**Comment by linawolf** [comment]
Deprecation: #94959 - ContentObjectRenderer constructor in StandaloneView hasn't been mentioned

**Comment by linawolf** [comment]
Deprecation: #94979 - Using CacheManager or Database Connections during TYPO3 bootstrap wasn't mentioned

**Comment by linawolf** [comment]
Deprecation: #95003 - Extbase ViewInterface canRender() was removed with [Deprecation] #94991 - Extbase AbstractView TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#473

**Comment by linawolf** [comment]
Deprecation: #95005 - Extbase EmptyView has not been mentioned

**Comment by linawolf** [comment]
Deprecation: #95011 - Various global JavaScript functions and variables -> not mentioned

**Comment by linawolf** [comment]
Deprecation: #95062 - $skipSorting argument of RelationHandler->writeForeignField() has not been mentioned

**Comment by linawolf** [comment]
Deprecation: #95065 - Hook extTablesInclusion-PostProcessing had non been mentioned

**Comment by linawolf** [comment]
Deprecation: #95077 - Filelist editIconsHook - not mentioned

**Comment by linawolf** [comment]
Deprecation: #95077 - FileDump CheckFileAccess hook - not mentioned

**Comment by linawolf** [comment]
Deprecation: #95083 - Backend toolbar CacheActions hook - not mentioned

**Comment by linawolf** [comment]
Deprecation: #95089 - ExtendedFileUtility ProcessData hook have not been mentioned

**Comment by linawolf** [comment]
Breaking: #70528 - Deprecated form mixins removed must be documented in the forms manual

**Comment by linawolf** [comment]
All changes have been worked on, all attached issues are merged

**Comment by linawolf** [comment]
Seems like we missed some changelog entries here

**Comment by linawolf** [comment]
Deprecation: #95009 - Passing TypoScript configuration as constructor argument to Exception handler not mentioned

**Comment by linawolf** [comment]
Deprecation: #95105 - DatabaseRecordList hooks never mentioned

**Comment by linawolf** [comment]
Everything is merged
