### ISSUE TITLE
Update docs for 11.5 (ongoing master issue)

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1522]
# Breaking

# Features

* [x] [Feature: #95176 - Introduce <f:transform.html> view helper](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-95176-IntroduceFtransformhtmlView-helper.html)

* [x] [Feature: #94868 - Introduce Bootstrap 5 compatible and accessible templates](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-94868-IntroduceBootstrap5CompatibleAndAccessibleTemplates.html)

* [x] [Feature: #95364 - Event to modify frontend user groups without authentication](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-95364-EventToModifyFrontendUserGroupsWithoutAuthentication.html)

# Deprecation

* [x] [Deprecation: #95041 - Deprecate <f:uri.email> view-helper](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-95041-DeprecateFuriemailView-helper.html)

* [x] [Deprecation: #95139 - Extbase ControllerContext](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-95139-ExtbaseControllerContext.html)

* [x] [Deprecation: #91787 - Deprecate inline JavaScript in fieldChangeFunc](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-91787-DeprecateInlineJavaScriptInFieldChangeFunc.html)

* [x] [Deprecation: #94094 - navigationFrameModule in Module Registration](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-94094-NavigationFrameModuleInModuleRegistration.html)

* [x] [Deprecation: #94791 - GeneralUtility::minifyJavaScript()](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-94791-GeneralUtilityminifyJavaScript.html)

* [x] [Deprecation: #95164 - ext:backend BackendTemplateView](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-95164-ExtbackendBackendTemplateView.html)

* [x] [Deprecation: #95219 - TypoScriptFrontendController->ATagParams](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-95219-TypoScriptFrontendController-ATagParams.html)

* [x] [Deprecation: #95222 - Extbase ViewInterface](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-95222-ExtbaseViewInterface.html)

* [x] [Deprecation: #95235 - Public getter of services in ModuleTemplate](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-95235-PublicGetterOfServicesInModuleTemplate.html)

* [x] [Deprecation: #95254 - Two FlexFormTools methods](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-95254-TwoFlexFormToolsMethods.html)

* [x] [Deprecation: #95257 - GeneralUtility::isFirstPartOfStr()](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-95257-GeneralUtilityisFirstPartOfStr.html)

* [x] [Deprecation: #95261 - Public methods in SectionMarkupGenerated events](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-95261-PublicMethodsInSectionMarkupGeneratedEvents.html)

* [x] [Deprecation: #95275 - RelationHandler->remapMM()](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-95275-RelationHandler-remapMM.html)

* [x] [Deprecation: #95293 - StringUtility::beginsWith() and StringUtility::endsWith()](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-95293-StringUtilitystartsWithAndStringUtilityendsWith.html)

* [x] [Deprecation: #95317 - Legacy syntax for IRRE localize synchronize command in DataHandler](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-95317-LegacySyntaxForIRRELocalizeSynchronizeCommandInDataHandler.html)

* [ ] [Deprecation: #95318 - TypoScript parseFunc.sword](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-95318-TypoScriptParseFuncsword.html)

* [x] [Deprecation: #95320 - Various method arguments in Authentication objects](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-95320-VariousMethodArgumentsInAuthenticationObjects.html)

* [x] [Deprecation: #95322 - Legacy Element Browser logic](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-95322-LegacyElementBrowserLogic.html)

* [x] [Deprecation: #95326 - Various “getInstance()” static methods on Singleton interfaces](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-95326-VariousGetInstanceStaticMethodsOnSingletonInterfaces.html)

* [x] [Deprecation: #95343 - Legacy hook for new content element wizard](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-95343-LegacyHookForNewContentElementWizard.html)

* [x] [Deprecation: #95349 - TypoScript: page.includeCSS/includeCSSLibs.import](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-95349-TypoScriptPageincludeCSSincludeCSSLibsimport.html)

* [x] [Deprecation: #95351 - Custom JSWindow options in HMENU settings](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-95351-CustomJSWindowOptionsInHMENUSettings.html)

* [x] [Deprecation: #95200 - Deprecate RequireJS callbacks as inline JavaScript](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-95200-DeprecateRequireJSCallbacksAsInlineJavaScript.html)

* [x] [Deprecation: #95367 - GeneralUtility::isAbsPath()](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-95367-GeneralUtilityisAbsPath.html)

* [x] [Deprecation: #91814 - Deprecate AbstractControl::setOnClick](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-91814-DeprecateAbstractControlsetOnClick.html)

# Important

* [x] [Important: #95261 - New public methods in SectionMarkupGenerated events](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Important-95261-NewPublicMethodsInSectionMarkupGeneratedEvents.html)

* [x] [Important: #95298 - Fluid Viewhelpers will be declared final in v12](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Important-95298-FluidViewhelpersWillBeDeclaredFinalInV12.html)

* [x] [Important: #95384 - TCA internal_type=db optional for type=group](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Important-95384-TCAInternal_typedbOptionalForTypegroup.html)

**Comment by linawolf** [comment]
Deprecation: #95041 - Deprecate <f:uri.email> view-helper Will be documented in Fluid Reference
Deprecation: #95139 - Extbase ControllerContext not mentioned in the docs

**Comment by linawolf** [comment]
Feature: #95176 - Introduce <f:transform.html> view helper -> View Helper Reference

**Comment by linawolf** [comment]
Deprecation: #94094 - navigationFrameModule in Module Registration -> Not mentioned

**Comment by linawolf** [comment]
Deprecation: #94791 - GeneralUtility::minifyJavaScript() wasnt mentioned

**Comment by linawolf** [comment]
Deprecation: #95219 - TypoScriptFrontendController->ATagParams wasnt mentioned

**Comment by linawolf** [comment]
Deprecation: #95235 - Public getter of services in ModuleTemplate has not been mentioned

**Comment by linawolf** [comment]
Deprecation: #95254 - Two FlexFormTools methods has not been mentioned

**Comment by linawolf** [comment]
Deprecation: #95257 - GeneralUtility::isFirstPartOfStr() is not mentioned

**Comment by linawolf** [comment]
accidently closed

**Comment by linawolf** [comment]
Deprecation: #95261 - Public methods in SectionMarkupGenerated events have not been mentioned

**Comment by linawolf** [comment]
Deprecation: #95275 - RelationHandler->remapMM() has not been mentioned

**Comment by linawolf** [comment]
Deprecation: #95293 - StringUtility::beginsWith() and StringUtility::endsWith() have not been mentioned

**Comment by linawolf** [comment]
Deprecation: #95317 - Legacy syntax for IRRE localize synchronize command in DataHandler 
already requests arrays: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Typo3CoreEngine/Database/Index.html#command-keywords-and-values

**Comment by linawolf** [comment]
Deprecation: #95318 - TypoScript parseFunc.sword has not been mentioned

**Comment by linawolf** [comment]
Deprecation: #95320 - Various method arguments in Authentication objects has not been mentioned

**Comment by linawolf** [comment]
Deprecation: #95322 - Legacy Element Browser logic has not been mentioned

**Comment by linawolf** [comment]
Deprecation: #95326 - Various “getInstance()” static methods on Singleton interfaces not mentioned

**Comment by linawolf** [comment]
Deprecation: #95343 - Legacy hook for new content element wizard not mentioned in master

**Comment by linawolf** [comment]
Deprecation: #95367 - GeneralUtility::isAbsPath() not mentioned anymore

**Comment by linawolf** [comment]
Important: #95261 - New public methods in SectionMarkupGenerated events not mentioned

**Comment by linawolf** [comment]
Important: #95298 - Fluid Viewhelpers will be declared final in v12 not mentioned

**Comment by linawolf** [comment]
Feature: #94868 - Introduce Bootstrap 5 compatible and accessible templates to be documented in EXT:form Documentation

**Comment by linawolf** [comment]
Deprecation: #91814 - Deprecate AbstractControl::setOnClick has not been mentioned
