### ISSUE TITLE
Update docs for 11.5.x

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1583]
```ddev exec php -f generate-changelog-issue.php 11.5.x 1583```

# Breaking

# Features

# Deprecation

* [x] [Deprecation: #95800 - Deprecate generating public URL for private asset files](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.5.x/Deprecation-95800-GeneratingPublicURLForPrivateAssetFiles.html)

# Important

* [x] [Bugfix: #93635 - Add mail configuration for setting smtp domain](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.5.x/Important-93635-AddMailConfigurationForSettingSmtpDomain.html)

* [x] [Important: #92020 - New API entry point available at https://get.typo3.org/api/](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.5.x/Important-92020-NewAPIEntryPointAvailableAtHttpsgettypo3orgapi.html)

* [x] [Important: #93635 - Add mail configuration for setting smtp domain](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.5.x/Important-93635-AddMailConfigurationForSettingSmtpDomain.html)

* [x] [Important: #96332 - Extbase Validators can use dependency injection](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.5.x/Important-96332-ExtbaseValidatorsCanUseDependencyInjection.html)

**Comment by linawolf** [comment]
All open Core Issues can be found here now: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues
