### ISSUE TITLE
Check status of AbstractPlugin

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1901]
## todos

* [ ] double-check statement that developing plugins with AbstractPlugin is not recommended
* [ ] either way, linking to a Changelog or "official" statement would be helpful
* [ ] if it is not recommended, might be good to add a note in the comment section of the class: https://github.com/TYPO3/typo3/blob/main/typo3/sysext/frontend/Classes/Plugin/AbstractPlugin.php
* if it is in fact not recommended, should this be listed in the Howto section?

## Background

The documentation states:

> Legacy frontend plugins without Extbase, so called “pi-based plugins” are based on the [AbstractPlugin](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/HowTo/FrontendPlugin/AbstractPlugin.html#abstractplugin). It is not recommended anymore to use the AbstractPlugin as base for new frontend plugins.

https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/HowTo/FrontendPlugin/Index.html

Can we check this? Last I heard, that was not true. I think it is more of a "it depends" kind of decision.

The fact that the core does not use it does not say anything - the core does not ship any plugins. While using Extbase (usually) makes the development more convenient - if AbstractPlugin were completely useless, I think it would be deprecated by now.

Also, see how core usually does _not_ use Extbase for backend modules (different topic, but here a non-Extbase approach is followed).

I really don't know at this point - might be a good idea to get (official) feedback here from "core" lead.

## Resources

Stack Overflow

> All previous answers have been correct but some words from a TYPO3 core team member: There are no plans to drop the support of "pibase" in the core. It is absolutely ok to use that API even though it does not provide much help to developers.

2017, so quite old, Georg Ringer
https://stackoverflow.com/a/48008460/2444812

...

Nothing found in changelog pertaining to status of AbstractPlugin.

**Comment by brotkrueml** [comment]
The AbstractPlugin is marked as internal in v12.0: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/171

**Comment by linawolf** [comment]
I pushed the issue forward now and the Abstract Plugin is marked as internal.
