### ISSUE TITLE
Improve backend modules chapter

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1902]
## problems

* it is neither a tutorial nor a reference
* Introduction is missing
* currently it is just a list of things what to do, unclear how this works
* some explanation why there are 2 ways to do things (with and without Extbase) and what to choose when
* the "with Extbase / without" is confusing. What is a good way to deal with this (e.g. create 2 entirely separate chapters, but there are some things which are the same for both ...)

![image](https://user-images.githubusercontent.com/13206455/172124046-fd897be7-7a67-4fff-83eb-698255130b97.png)

* there is a page with just the title "Without Extbase:" - looks like a mistake

![image](https://user-images.githubusercontent.com/13206455/172123822-31a1d646-a2d6-43ba-8ad0-f83296ff5128.png)

## todos

I think we can address the issues one by one:

* [ ] **Introduction** missing. Also explain what backend modules are and how this works
* [ ] Unclear, which of these parts you actually needed - it is just a list of building blocks and the **glue** is missing. Possibly a "quickstart" with the basic steps and the rest as a reference might solve this.
* [ ] it is not a reference, and not a tutorial - I think we should have both, maybe a tutorial on a "quickstart" page and possibly a reference
* [ ] Explain when to use Extbase, when not to
* [ ] give the "Without Extbase:" page a proper title
* [ ] Also, should this be in "Extension development" chapter? It used to be on the top level. "Content elements and plugins" are on the top level - I have mixed feelings about this.

**Comment by sypets** [comment]
Has been reworked
