### ISSUE TITLE
SEO - improve findability of some key features: TSFE

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#2666]
**Edit**: _Issue was updated._

Right now, when searching for TSFE on Google, these are my first hits:

1. TYPO3 9, Page TSconfig: https://docs.typo3.org/m/typo3/reference-tsconfig/9.5/en-us/PageTsconfig/Tsfe.html
2. community resource
3. community resource
4. ...

Problem with result 1: is old page, and you can't switch with version selector to newer page (which is correct, because functionality was removed). Also Page TSconfig is probably not the most relevant thing here. See also https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TSconfig/issues/331

Problem with (some of the) community resources: are not always kept updated and often do not list TYPO3 versions for which this applies, are sometimes in German, most often do not have a version selector.  (A nice exception which show TYPO3 versions are pages by Sebastian Klein, Daniel Goerz and Daniel Siepmann)

## todos

- [x] Add deprecation note to [Page TSconfig TSE page](https://docs.typo3.org/m/typo3/reference-tsconfig/9.5/en-us/PageTsconfig/Tsfe.html)
- [x] create page for TSFE. From there provide links to other info, e.g. in TypoScript reference, in PR: #2736
- [x] add info and link to global variables page: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/Configuration/GlobalVariables.html, in PR: #2736
- [ ] add cross links within documentation
   -  link to main TSFE page in T3'Explained from [TSconfig TSFE](https://docs.typo3.org/m/typo3/reference-tsconfig/9.5/en-us/PageTsconfig/Tsfe.html)
   -  link to main TSFE page in T3'Explained from[ TypoSript TSFE section](https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/Functions/Data.html?highlight=tsfe#tsfe)
   - link to main TSFE in [FormEngine docs page where TSFE is mentioned](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/FormEngine/Introduction/Index.html)
- [ ] possibly correct / amend some outdated answers on Stack Overflow and link to new docs page (not responsibility of docs team, but cool if someone could look into it)

This should "catch" some of the search engine results (hopefully "outranking" the outdated TSconfig page) **and** provide missing information and cross links.

## Resources

documentation Pages about TSFE (directly or slightly related):

* frontend.controller  request attribute: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/RequestLifeCycle/RequestAttributes/FrontendController.html
* FormEngine: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/FormEngine/Introduction/Index.html

other sources which use TSFE

* https://stackoverflow.com/questions/19363981/typo3-reference-about-tsfe-array (this also asks for references)
* [How to correctly initialize $GLOBALS['TSFE']](https://stackoverflow.com/questions/43179076/how-to-correctly-initialize-globalstsfe): accepted and most upvoted answer has snippet to initialize without context - this is not only bad advice in at least some cases but does not help to clarify 
* [How to access $GLOBALS['TSFE'] in TYPO3 v10](https://stackoverflow.com/questions/66027637/how-to-access-globalstsfe-in-typo3-v10)

**Comment by DavidBruchmann** [comment]
Currently I can switch the version on your 1st search result https://docs.typo3.org/m/typo3/reference-tsconfig/9.5/en-us/PageTsconfig/.
Does this solve the issue perhaps already?

**Comment by sypets** [comment]
> Currently I can switch the version on your 1st search result https://docs.typo3.org/m/typo3/reference-tsconfig/9.5/en-us/PageTsconfig/. Does this solve the issue perhaps already?

I don't think so. The TSFE one is this one: https://docs.typo3.org/m/typo3/reference-tsconfig/9.5/en-us/PageTsconfig/Tsfe.html

**Comment by DavidBruchmann** [comment]
Ok, I see, the TSFE page is missing for versions 10, 11 and main.

Did you see this change?

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.0/Breaking-88564-PageTSconfigSettingTSFEconstantsRemoved.html?highlight=tsfe

**Comment by sypets** [comment]
Yes, it has been removed in the newer versions. That is not the problem. The problem is (or may be), 

* there is no info about the deprecation / removal for the page  https://docs.typo3.org/m/typo3/reference-tsconfig/9.5/en-us/PageTsconfig/Tsfe.html
* you search for a general thing (TSFE) which is used in several contexts

There is an easy fix for this, but it is also a general thing that can be addressed.

The easy fix can be:

* add info about deprecation
* possibly, you add info about TSFE in TYPO3 explained

I have assigned myself the issue. I will take a look.
