### ISSUE TITLE
Menu + structure

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#735]
A PR #634 has already been merged.

I would like to collect some further ideas here for the future ...

## Problem

* current "API Overview" has exploded: more than 70 items. Still more are being added. 
* there are still some items in top menu, some in "API Overview" and some in "Extension Development". Not always does this make sense
* the current sorting by category is not intuitive for sorting in the menu - as it is not possible to add captions to second level menu, the sorting seems arbitrary - people expect alphabetical sorting

## Considerations

* in general, it has been proven a problem, if items are hidden in submenus (especially if there are several submenu levels)
* on the other hand, huge long lists in menu are not very helpful either. 

## Approach

* all items in "API Overview" are moved to top menu
* the item are sorted alphabetially
* we add "Quick links" menu and quick links to start page with most relevant (often searched for and often viewed) pages
* we gradually try to find common broader categories and move some items to second level. This has been done for configuration, SEO, "Content Elements & Plugins". This has the additional advantage that we create "entry pages" for a topic which give an introduction and overview comparing the various methods (if there are several). We did this for example for [configuration](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Configuration/Index.html).
* **We do not move or rename the files**. This creates broken links (or redirects must be added which is a lot of work). This has the disadvantage that the menu and the file structure differ in some places. We try to be careful and not change too much as this is not well maintainable. 

## Todo

* [ ] split up "Extension Development" and move to main menu too
* [ ] possibly split up "STEPS TOWARDS CREATING AN EXTENSION" into a separate "getting started with extension development" guide
* [ ] Examples is currently not in menu, pages must be reavalutated and migrated as well
* data formats is handled in separate patch
* [ ] remove some stuff from start page so you don't have to scroll down so much to reach the table of contents?

Possibly continue with finding broader categories. Currenty, there are lots of very small topics on top level. Some of these are just one interface. 

examples:

* enumerations
* broadcast channels
* pagination

**Comment by sypets** [comment]
The current state being (for reference in the future):

* Quick links
* Introduction
* Extension Development (with "Introduction" to Extensions, "Reserved files" and "Steps towards creating an extension")
* TYPO3 A-Z with all topics on top level, sorted alphabetically


Here is some feedback for the current state:

Twitter:
![image](https://user-images.githubusercontent.com/13206455/89106298-10deb580-d429-11ea-9810-ae085fd998cb.png)


Slack:

![image](https://user-images.githubusercontent.com/13206455/89106318-3b307300-d429-11ea-8235-b3f1175ffda4.png)

**Comment by linawolf** [comment]
@sypets, are you still working on this topic? If not please remove the Doing label and lets find someone else to work on it. This is a really important topic to move forward with I think.

**Comment by susannemoog** [comment]
@linawolf I would postpone the restructuring ticket until we finish with the wiki migration, to avoid too many bigger open topics (if there is someone else who wants to take care, that would be fine, too). After that, I think we should have a short sprint to define a better structure and directly implement that.
