### ISSUE TITLE
Documentation updates related to Changelog 9.1

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#887]
**Note**: Since this issue was created after some changes were already made to the documentation, not all done changelogs have been checked (yet) in this list. If you find items that are done, please mark them as checked or leave a comment. (You need write permissions to check an item. It's ok to just leave a comment, if you don't have permission).

----

Workflow for updating docs based on Change is documented on https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/HowToUpdateDocs.html

----

Breaking

* [x] [Breaking: #83638 - Redirect functionality moved from sys_domain to redirects module](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.1/Breaking-83638-RedirectFunctionalityMovedFromSys_domainToRedirectsModule.html)

Features

* [x] [Feature: #61170 - Add additional hook for record list](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.1/Feature-61170-AddAdditionalHookForRecordList.html)

* [x] [Feature: #83350 - Add recursive filtering of arrays](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.1/Feature-83350-AddRecursiveArrayFiltering.html)

* [x] [Feature: #83429 - Feature Toggles](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.1/Feature-83429-FeatureToggles.html)

* [x] [Feature: #83449 - Make list of fields configurable in Pagetree overview in Info module](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.1/Feature-83449-MakeListOfFieldsConfigurableInPagetreeOverviewInInfoModule.html) (see [Pull request](https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TSconfig/pull/110))

* [x] [Feature: #83461 - Show fieldname next to title in debug mode](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.1/Feature-83461-ShowFieldnameNextToTitleInDebugMode.html)

* [x] [Feature: #83529 - Execute hooks on backend user login](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.1/Feature-83529-ExecuteHooksOnBackendUserLogin.html)

* [x] [Feature: #83631 - System Extension “redirects” has been added](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.1/Feature-83631-SystemExtensionRedirectsHasBeenAdded.html)

> There is already a forge issue for documenting the redirects extension: https://forge.typo3.org/issues/88570

* [x] [Feature: #83637 - Added new main module “Site Management”](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.1/Feature-83637-AddedNewMainModuleSiteManagement.html)

* [ ] [Feature: #83677 - Globally disable/enable redirect hit statistics](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.1/Feature-83677-GloballyDisableenableRedirectHitStatistics.html)

> There is already a forge issue for documenting the redirects extension: https://forge.typo3.org/issues/88570

Deprecation

* [x] [Deprecation: #81852 - Deprecated Usage of EXT:rsaauth](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.1/Deprecation-81852-DeprecatedUsageOfEXTrsaauth.html)

* [x] [Deprecation: #83503 - Deprecate unneeded RawValidator](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.1/Deprecation-83503-DeprecateUnneededRawValidator.html)

* [x] [Deprecation: #83511 - Deprecate AbstractValidatorTestcase](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.1/Deprecation-83511-DeprecateAbstractValidatorTestcase.html)

* [x] [Deprecation: #83592 - impexp: Removed “Maximum number of records” restriction](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.1/Deprecation-83592-ImpexpRemovedMaximumNumberOfRecordsRestriction.html)

* [x] [Deprecation: #83596 - impexp: Removed “Max file size” restriction](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.1/Deprecation-83596-ImpexpRemovedMaxFileSizeRestriction.html)

* [x] [Deprecation: #83606 - impexp: Size handling removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.1/Deprecation-83606-ImpexpSizeHandlingRemoved.html)

Important

none
